version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=newwork_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  #    Uncomment the following lines to expose PostgreSQL port to host.
  #    ports:
  #      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080" # Spring Boot runs on 8080 by default
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/newwork_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      # Add Hugging Face key later

volumes:
  postgres_data: